/// Flutter icons CandlyIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CandlyIcons
///      fonts:
///       - asset: fonts/CandlyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CandlyIcons {
  CandlyIcons._();

  static const _kFontFam = 'CandlyIcons';
  static const String? _kFontPkg = null;

  static const IconData property_1_close = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_done = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_error = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_info = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_linkedin = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_location = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_loss = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_mail = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_phone = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_send = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_wallet = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_account = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_add = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_arrow_down = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_arrow_left = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_arrow_right = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData property_1_arrow_up = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
